// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVedzYyG8fvIb0-hkcIciZsOT55wxIlXQ',
    appId: '1:683824231194:web:13fb477d802c62038732a3',
    messagingSenderId: '683824231194',
    projectId: 'crowdcash-app-backend',
    authDomain: 'crowdcash-app-backend.firebaseapp.com',
    storageBucket: 'crowdcash-app-backend.appspot.com',
    measurementId: 'G-113FJ1KFYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-hApTxab_03a0jqPJLWCW77B1PtW4Ipk',
    appId: '1:683824231194:android:dc44d775350d49158732a3',
    messagingSenderId: '683824231194',
    projectId: 'crowdcash-app-backend',
    storageBucket: 'crowdcash-app-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt7S8IwrAEMKWFIG04Bl2T98-TZaXNreA',
    appId: '1:683824231194:ios:1cbb08b9f8fb4daa8732a3',
    messagingSenderId: '683824231194',
    projectId: 'crowdcash-app-backend',
    storageBucket: 'crowdcash-app-backend.appspot.com',
    iosBundleId: 'com.example.crowdcashV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt7S8IwrAEMKWFIG04Bl2T98-TZaXNreA',
    appId: '1:683824231194:ios:1cbb08b9f8fb4daa8732a3',
    messagingSenderId: '683824231194',
    projectId: 'crowdcash-app-backend',
    storageBucket: 'crowdcash-app-backend.appspot.com',
    iosBundleId: 'com.example.crowdcashV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVedzYyG8fvIb0-hkcIciZsOT55wxIlXQ',
    appId: '1:683824231194:web:fa9fbb9ad7a5883b8732a3',
    messagingSenderId: '683824231194',
    projectId: 'crowdcash-app-backend',
    authDomain: 'crowdcash-app-backend.firebaseapp.com',
    storageBucket: 'crowdcash-app-backend.appspot.com',
    measurementId: 'G-Z820RXZCSL',
  );
}
